//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeighBridgeApplication.RustiviaSolution.DbService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WeighBridgeInfoDto", Namespace="http://schemas.datacontract.org/2004/07/RustiviaSolutions.Service.DTO")]
    [System.SerializableAttribute()]
    public partial class WeighBridgeInfoDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WeighBridgeApplication.RustiviaSolution.DbService.DriverDto DriverField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal FirstMassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal NettMassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SecondMassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WeighBridgeApplication.RustiviaSolution.DbService.TruckDto TruckDtoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comments {
            get {
                return this.CommentsField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentsField, value) != true)) {
                    this.CommentsField = value;
                    this.RaisePropertyChanged("Comments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WeighBridgeApplication.RustiviaSolution.DbService.DriverDto Driver {
            get {
                return this.DriverField;
            }
            set {
                if ((object.ReferenceEquals(this.DriverField, value) != true)) {
                    this.DriverField = value;
                    this.RaisePropertyChanged("Driver");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal FirstMass {
            get {
                return this.FirstMassField;
            }
            set {
                if ((this.FirstMassField.Equals(value) != true)) {
                    this.FirstMassField = value;
                    this.RaisePropertyChanged("FirstMass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal NettMass {
            get {
                return this.NettMassField;
            }
            set {
                if ((this.NettMassField.Equals(value) != true)) {
                    this.NettMassField = value;
                    this.RaisePropertyChanged("NettMass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SecondMass {
            get {
                return this.SecondMassField;
            }
            set {
                if ((this.SecondMassField.Equals(value) != true)) {
                    this.SecondMassField = value;
                    this.RaisePropertyChanged("SecondMass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WeighBridgeApplication.RustiviaSolution.DbService.TruckDto TruckDto {
            get {
                return this.TruckDtoField;
            }
            set {
                if ((object.ReferenceEquals(this.TruckDtoField, value) != true)) {
                    this.TruckDtoField = value;
                    this.RaisePropertyChanged("TruckDto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DriverDto", Namespace="http://schemas.datacontract.org/2004/07/RustiviaSolutions.Service.DTO")]
    [System.SerializableAttribute()]
    public partial class DriverDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdLocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WeighBridgeApplication.RustiviaSolution.DbService.SupplierInfoDto SupplierInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VatFormLocationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Firstname {
            get {
                return this.FirstnameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstnameField, value) != true)) {
                    this.FirstnameField = value;
                    this.RaisePropertyChanged("Firstname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdLocation {
            get {
                return this.IdLocationField;
            }
            set {
                if ((object.ReferenceEquals(this.IdLocationField, value) != true)) {
                    this.IdLocationField = value;
                    this.RaisePropertyChanged("IdLocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdNumber {
            get {
                return this.IdNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.IdNumberField, value) != true)) {
                    this.IdNumberField = value;
                    this.RaisePropertyChanged("IdNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageName {
            get {
                return this.ImageNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageNameField, value) != true)) {
                    this.ImageNameField = value;
                    this.RaisePropertyChanged("ImageName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WeighBridgeApplication.RustiviaSolution.DbService.SupplierInfoDto SupplierInfo {
            get {
                return this.SupplierInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.SupplierInfoField, value) != true)) {
                    this.SupplierInfoField = value;
                    this.RaisePropertyChanged("SupplierInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VatFormLocation {
            get {
                return this.VatFormLocationField;
            }
            set {
                if ((object.ReferenceEquals(this.VatFormLocationField, value) != true)) {
                    this.VatFormLocationField = value;
                    this.RaisePropertyChanged("VatFormLocation");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TruckDto", Namespace="http://schemas.datacontract.org/2004/07/RustiviaSolutions.Service.DTO")]
    [System.SerializableAttribute()]
    public partial class TruckDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool OwnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WeighBridgeApplication.RustiviaSolution.DbService.SupplierInfo SupplierInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TruckRegNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WeighBridgeApplication.RustiviaSolution.DbService.WeighBridgeInfo[] WeighBridgeInfoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Own {
            get {
                return this.OwnField;
            }
            set {
                if ((this.OwnField.Equals(value) != true)) {
                    this.OwnField = value;
                    this.RaisePropertyChanged("Own");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WeighBridgeApplication.RustiviaSolution.DbService.SupplierInfo SupplierInfo {
            get {
                return this.SupplierInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.SupplierInfoField, value) != true)) {
                    this.SupplierInfoField = value;
                    this.RaisePropertyChanged("SupplierInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TruckRegNumber {
            get {
                return this.TruckRegNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.TruckRegNumberField, value) != true)) {
                    this.TruckRegNumberField = value;
                    this.RaisePropertyChanged("TruckRegNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WeighBridgeApplication.RustiviaSolution.DbService.WeighBridgeInfo[] WeighBridgeInfo {
            get {
                return this.WeighBridgeInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.WeighBridgeInfoField, value) != true)) {
                    this.WeighBridgeInfoField = value;
                    this.RaisePropertyChanged("WeighBridgeInfo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SupplierInfoDto", Namespace="http://schemas.datacontract.org/2004/07/RustiviaSolutions.Service.DTO")]
    [System.SerializableAttribute()]
    public partial class SupplierInfoDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyRegNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WeighBridgeApplication.RustiviaSolution.DbService.DriverDto[] DriversField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LegalnoteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LogoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SupplierNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SuppliercodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TellNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WeighBridgeApplication.RustiviaSolution.DbService.TruckDto[] TrucksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VatNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyRegNumber {
            get {
                return this.CompanyRegNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyRegNumberField, value) != true)) {
                    this.CompanyRegNumberField = value;
                    this.RaisePropertyChanged("CompanyRegNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WeighBridgeApplication.RustiviaSolution.DbService.DriverDto[] Drivers {
            get {
                return this.DriversField;
            }
            set {
                if ((object.ReferenceEquals(this.DriversField, value) != true)) {
                    this.DriversField = value;
                    this.RaisePropertyChanged("Drivers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Legalnote {
            get {
                return this.LegalnoteField;
            }
            set {
                if ((object.ReferenceEquals(this.LegalnoteField, value) != true)) {
                    this.LegalnoteField = value;
                    this.RaisePropertyChanged("Legalnote");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Logo {
            get {
                return this.LogoField;
            }
            set {
                if ((object.ReferenceEquals(this.LogoField, value) != true)) {
                    this.LogoField = value;
                    this.RaisePropertyChanged("Logo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SupplierName {
            get {
                return this.SupplierNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SupplierNameField, value) != true)) {
                    this.SupplierNameField = value;
                    this.RaisePropertyChanged("SupplierName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Suppliercode {
            get {
                return this.SuppliercodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SuppliercodeField, value) != true)) {
                    this.SuppliercodeField = value;
                    this.RaisePropertyChanged("Suppliercode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TellNumber {
            get {
                return this.TellNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.TellNumberField, value) != true)) {
                    this.TellNumberField = value;
                    this.RaisePropertyChanged("TellNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WeighBridgeApplication.RustiviaSolution.DbService.TruckDto[] Trucks {
            get {
                return this.TrucksField;
            }
            set {
                if ((object.ReferenceEquals(this.TrucksField, value) != true)) {
                    this.TrucksField = value;
                    this.RaisePropertyChanged("Trucks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VatNumber {
            get {
                return this.VatNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.VatNumberField, value) != true)) {
                    this.VatNumberField = value;
                    this.RaisePropertyChanged("VatNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SupplierInfo", Namespace="http://schemas.datacontract.org/2004/07/RustiviaSolutions.Models")]
    [System.SerializableAttribute()]
    public partial class SupplierInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyRegNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WeighBridgeApplication.RustiviaSolution.DbService.Driver[] DriversField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LegalnoteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LogoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SupplierNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SuppliercodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TellNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WeighBridgeApplication.RustiviaSolution.DbService.Truck[] TrucksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VatNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyRegNumber {
            get {
                return this.CompanyRegNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyRegNumberField, value) != true)) {
                    this.CompanyRegNumberField = value;
                    this.RaisePropertyChanged("CompanyRegNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WeighBridgeApplication.RustiviaSolution.DbService.Driver[] Drivers {
            get {
                return this.DriversField;
            }
            set {
                if ((object.ReferenceEquals(this.DriversField, value) != true)) {
                    this.DriversField = value;
                    this.RaisePropertyChanged("Drivers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Legalnote {
            get {
                return this.LegalnoteField;
            }
            set {
                if ((object.ReferenceEquals(this.LegalnoteField, value) != true)) {
                    this.LegalnoteField = value;
                    this.RaisePropertyChanged("Legalnote");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Logo {
            get {
                return this.LogoField;
            }
            set {
                if ((object.ReferenceEquals(this.LogoField, value) != true)) {
                    this.LogoField = value;
                    this.RaisePropertyChanged("Logo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SupplierName {
            get {
                return this.SupplierNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SupplierNameField, value) != true)) {
                    this.SupplierNameField = value;
                    this.RaisePropertyChanged("SupplierName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Suppliercode {
            get {
                return this.SuppliercodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SuppliercodeField, value) != true)) {
                    this.SuppliercodeField = value;
                    this.RaisePropertyChanged("Suppliercode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TellNumber {
            get {
                return this.TellNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.TellNumberField, value) != true)) {
                    this.TellNumberField = value;
                    this.RaisePropertyChanged("TellNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WeighBridgeApplication.RustiviaSolution.DbService.Truck[] Trucks {
            get {
                return this.TrucksField;
            }
            set {
                if ((object.ReferenceEquals(this.TrucksField, value) != true)) {
                    this.TrucksField = value;
                    this.RaisePropertyChanged("Trucks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VatNumber {
            get {
                return this.VatNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.VatNumberField, value) != true)) {
                    this.VatNumberField = value;
                    this.RaisePropertyChanged("VatNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WeighBridgeInfo", Namespace="http://schemas.datacontract.org/2004/07/RustiviaSolutions.Models")]
    [System.SerializableAttribute()]
    public partial class WeighBridgeInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WeighBridgeApplication.RustiviaSolution.DbService.Driver DriverField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal FirstMassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal NettMassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WeighBridgeApplication.RustiviaSolution.DbService.PastelInfo PastelInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaymentReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaymentTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SecondMassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SlipLocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WeighBridgeApplication.RustiviaSolution.DbService.Truck TruckField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comments {
            get {
                return this.CommentsField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentsField, value) != true)) {
                    this.CommentsField = value;
                    this.RaisePropertyChanged("Comments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WeighBridgeApplication.RustiviaSolution.DbService.Driver Driver {
            get {
                return this.DriverField;
            }
            set {
                if ((object.ReferenceEquals(this.DriverField, value) != true)) {
                    this.DriverField = value;
                    this.RaisePropertyChanged("Driver");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal FirstMass {
            get {
                return this.FirstMassField;
            }
            set {
                if ((this.FirstMassField.Equals(value) != true)) {
                    this.FirstMassField = value;
                    this.RaisePropertyChanged("FirstMass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal NettMass {
            get {
                return this.NettMassField;
            }
            set {
                if ((this.NettMassField.Equals(value) != true)) {
                    this.NettMassField = value;
                    this.RaisePropertyChanged("NettMass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WeighBridgeApplication.RustiviaSolution.DbService.PastelInfo PastelInfo {
            get {
                return this.PastelInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.PastelInfoField, value) != true)) {
                    this.PastelInfoField = value;
                    this.RaisePropertyChanged("PastelInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentReference {
            get {
                return this.PaymentReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentReferenceField, value) != true)) {
                    this.PaymentReferenceField = value;
                    this.RaisePropertyChanged("PaymentReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentType {
            get {
                return this.PaymentTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentTypeField, value) != true)) {
                    this.PaymentTypeField = value;
                    this.RaisePropertyChanged("PaymentType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SecondMass {
            get {
                return this.SecondMassField;
            }
            set {
                if ((this.SecondMassField.Equals(value) != true)) {
                    this.SecondMassField = value;
                    this.RaisePropertyChanged("SecondMass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SlipLocation {
            get {
                return this.SlipLocationField;
            }
            set {
                if ((object.ReferenceEquals(this.SlipLocationField, value) != true)) {
                    this.SlipLocationField = value;
                    this.RaisePropertyChanged("SlipLocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WeighBridgeApplication.RustiviaSolution.DbService.Truck Truck {
            get {
                return this.TruckField;
            }
            set {
                if ((object.ReferenceEquals(this.TruckField, value) != true)) {
                    this.TruckField = value;
                    this.RaisePropertyChanged("Truck");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Driver", Namespace="http://schemas.datacontract.org/2004/07/RustiviaSolutions.Models")]
    [System.SerializableAttribute()]
    public partial class Driver : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdLocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WeighBridgeApplication.RustiviaSolution.DbService.SupplierInfo SupplierInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VatFormLocationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Firstname {
            get {
                return this.FirstnameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstnameField, value) != true)) {
                    this.FirstnameField = value;
                    this.RaisePropertyChanged("Firstname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdLocation {
            get {
                return this.IdLocationField;
            }
            set {
                if ((object.ReferenceEquals(this.IdLocationField, value) != true)) {
                    this.IdLocationField = value;
                    this.RaisePropertyChanged("IdLocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdNumber {
            get {
                return this.IdNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.IdNumberField, value) != true)) {
                    this.IdNumberField = value;
                    this.RaisePropertyChanged("IdNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageName {
            get {
                return this.ImageNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageNameField, value) != true)) {
                    this.ImageNameField = value;
                    this.RaisePropertyChanged("ImageName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WeighBridgeApplication.RustiviaSolution.DbService.SupplierInfo SupplierInfo {
            get {
                return this.SupplierInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.SupplierInfoField, value) != true)) {
                    this.SupplierInfoField = value;
                    this.RaisePropertyChanged("SupplierInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VatFormLocation {
            get {
                return this.VatFormLocationField;
            }
            set {
                if ((object.ReferenceEquals(this.VatFormLocationField, value) != true)) {
                    this.VatFormLocationField = value;
                    this.RaisePropertyChanged("VatFormLocation");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Truck", Namespace="http://schemas.datacontract.org/2004/07/RustiviaSolutions.Models")]
    [System.SerializableAttribute()]
    public partial class Truck : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool OwnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WeighBridgeApplication.RustiviaSolution.DbService.SupplierInfo SupplierInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TruckRegNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WeighBridgeApplication.RustiviaSolution.DbService.WeighBridgeInfo[] WeighBridgeInfoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Own {
            get {
                return this.OwnField;
            }
            set {
                if ((this.OwnField.Equals(value) != true)) {
                    this.OwnField = value;
                    this.RaisePropertyChanged("Own");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WeighBridgeApplication.RustiviaSolution.DbService.SupplierInfo SupplierInfo {
            get {
                return this.SupplierInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.SupplierInfoField, value) != true)) {
                    this.SupplierInfoField = value;
                    this.RaisePropertyChanged("SupplierInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TruckRegNumber {
            get {
                return this.TruckRegNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.TruckRegNumberField, value) != true)) {
                    this.TruckRegNumberField = value;
                    this.RaisePropertyChanged("TruckRegNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WeighBridgeApplication.RustiviaSolution.DbService.WeighBridgeInfo[] WeighBridgeInfo {
            get {
                return this.WeighBridgeInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.WeighBridgeInfoField, value) != true)) {
                    this.WeighBridgeInfoField = value;
                    this.RaisePropertyChanged("WeighBridgeInfo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PastelInfo", Namespace="http://schemas.datacontract.org/2004/07/RustiviaSolutions.Models")]
    [System.SerializableAttribute()]
    public partial class PastelInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileLocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PastelNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WeighBridgeApplication.RustiviaSolution.DbService.WeighBridgeInfo WeighBridgeInfoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileLocation {
            get {
                return this.FileLocationField;
            }
            set {
                if ((object.ReferenceEquals(this.FileLocationField, value) != true)) {
                    this.FileLocationField = value;
                    this.RaisePropertyChanged("FileLocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PastelNumber {
            get {
                return this.PastelNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PastelNumberField, value) != true)) {
                    this.PastelNumberField = value;
                    this.RaisePropertyChanged("PastelNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WeighBridgeApplication.RustiviaSolution.DbService.WeighBridgeInfo WeighBridgeInfo {
            get {
                return this.WeighBridgeInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.WeighBridgeInfoField, value) != true)) {
                    this.WeighBridgeInfoField = value;
                    this.RaisePropertyChanged("WeighBridgeInfo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RustiviaSolution.DbService.IDataContext")]
    public interface IDataContext {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataContext/AddWeighBridgeInfo", ReplyAction="http://tempuri.org/IDataContext/AddWeighBridgeInfoResponse")]
        void AddWeighBridgeInfo(WeighBridgeApplication.RustiviaSolution.DbService.WeighBridgeInfoDto weighBridgeInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataContext/AddWeighBridgeInfo", ReplyAction="http://tempuri.org/IDataContext/AddWeighBridgeInfoResponse")]
        System.Threading.Tasks.Task AddWeighBridgeInfoAsync(WeighBridgeApplication.RustiviaSolution.DbService.WeighBridgeInfoDto weighBridgeInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataContext/GetTrucks", ReplyAction="http://tempuri.org/IDataContext/GetTrucksResponse")]
        WeighBridgeApplication.RustiviaSolution.DbService.TruckDto[] GetTrucks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataContext/GetTrucks", ReplyAction="http://tempuri.org/IDataContext/GetTrucksResponse")]
        System.Threading.Tasks.Task<WeighBridgeApplication.RustiviaSolution.DbService.TruckDto[]> GetTrucksAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataContext/GetDrivers", ReplyAction="http://tempuri.org/IDataContext/GetDriversResponse")]
        WeighBridgeApplication.RustiviaSolution.DbService.DriverDto[] GetDrivers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataContext/GetDrivers", ReplyAction="http://tempuri.org/IDataContext/GetDriversResponse")]
        System.Threading.Tasks.Task<WeighBridgeApplication.RustiviaSolution.DbService.DriverDto[]> GetDriversAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataContext/GetSuppliers", ReplyAction="http://tempuri.org/IDataContext/GetSuppliersResponse")]
        WeighBridgeApplication.RustiviaSolution.DbService.SupplierInfoDto[] GetSuppliers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataContext/GetSuppliers", ReplyAction="http://tempuri.org/IDataContext/GetSuppliersResponse")]
        System.Threading.Tasks.Task<WeighBridgeApplication.RustiviaSolution.DbService.SupplierInfoDto[]> GetSuppliersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataContext/GetWeighBridgeInfo", ReplyAction="http://tempuri.org/IDataContext/GetWeighBridgeInfoResponse")]
        WeighBridgeApplication.RustiviaSolution.DbService.WeighBridgeInfoDto[] GetWeighBridgeInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataContext/GetWeighBridgeInfo", ReplyAction="http://tempuri.org/IDataContext/GetWeighBridgeInfoResponse")]
        System.Threading.Tasks.Task<WeighBridgeApplication.RustiviaSolution.DbService.WeighBridgeInfoDto[]> GetWeighBridgeInfoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataContext/IsValidUser", ReplyAction="http://tempuri.org/IDataContext/IsValidUserResponse")]
        bool IsValidUser(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataContext/IsValidUser", ReplyAction="http://tempuri.org/IDataContext/IsValidUserResponse")]
        System.Threading.Tasks.Task<bool> IsValidUserAsync(string userName, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDataContextChannel : WeighBridgeApplication.RustiviaSolution.DbService.IDataContext, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataContextClient : System.ServiceModel.ClientBase<WeighBridgeApplication.RustiviaSolution.DbService.IDataContext>, WeighBridgeApplication.RustiviaSolution.DbService.IDataContext {
        
        public DataContextClient() {
        }
        
        public DataContextClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataContextClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataContextClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataContextClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddWeighBridgeInfo(WeighBridgeApplication.RustiviaSolution.DbService.WeighBridgeInfoDto weighBridgeInfo) {
            base.Channel.AddWeighBridgeInfo(weighBridgeInfo);
        }
        
        public System.Threading.Tasks.Task AddWeighBridgeInfoAsync(WeighBridgeApplication.RustiviaSolution.DbService.WeighBridgeInfoDto weighBridgeInfo) {
            return base.Channel.AddWeighBridgeInfoAsync(weighBridgeInfo);
        }
        
        public WeighBridgeApplication.RustiviaSolution.DbService.TruckDto[] GetTrucks() {
            return base.Channel.GetTrucks();
        }
        
        public System.Threading.Tasks.Task<WeighBridgeApplication.RustiviaSolution.DbService.TruckDto[]> GetTrucksAsync() {
            return base.Channel.GetTrucksAsync();
        }
        
        public WeighBridgeApplication.RustiviaSolution.DbService.DriverDto[] GetDrivers() {
            return base.Channel.GetDrivers();
        }
        
        public System.Threading.Tasks.Task<WeighBridgeApplication.RustiviaSolution.DbService.DriverDto[]> GetDriversAsync() {
            return base.Channel.GetDriversAsync();
        }
        
        public WeighBridgeApplication.RustiviaSolution.DbService.SupplierInfoDto[] GetSuppliers() {
            return base.Channel.GetSuppliers();
        }
        
        public System.Threading.Tasks.Task<WeighBridgeApplication.RustiviaSolution.DbService.SupplierInfoDto[]> GetSuppliersAsync() {
            return base.Channel.GetSuppliersAsync();
        }
        
        public WeighBridgeApplication.RustiviaSolution.DbService.WeighBridgeInfoDto[] GetWeighBridgeInfo() {
            return base.Channel.GetWeighBridgeInfo();
        }
        
        public System.Threading.Tasks.Task<WeighBridgeApplication.RustiviaSolution.DbService.WeighBridgeInfoDto[]> GetWeighBridgeInfoAsync() {
            return base.Channel.GetWeighBridgeInfoAsync();
        }
        
        public bool IsValidUser(string userName, string password) {
            return base.Channel.IsValidUser(userName, password);
        }
        
        public System.Threading.Tasks.Task<bool> IsValidUserAsync(string userName, string password) {
            return base.Channel.IsValidUserAsync(userName, password);
        }
    }
}
