//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeighBridgeApplication.RustiviaService.DbContext {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PurchaseDto", Namespace="http://schemas.datacontract.org/2004/07/IntroductionMVC5.Service.DTOs")]
    [System.SerializableAttribute()]
    public partial class PurchaseDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WeighBridgeApplication.RustiviaService.DbContext.DriverDto DriverField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WeighBridgeApplication.RustiviaService.DbContext.TruckDto TruckField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WeighBridgeApplication.RustiviaService.DbContext.WeighBridgeInfoDto WeighBridgeInfoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WeighBridgeApplication.RustiviaService.DbContext.DriverDto Driver {
            get {
                return this.DriverField;
            }
            set {
                if ((object.ReferenceEquals(this.DriverField, value) != true)) {
                    this.DriverField = value;
                    this.RaisePropertyChanged("Driver");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalPrice {
            get {
                return this.TotalPriceField;
            }
            set {
                if ((this.TotalPriceField.Equals(value) != true)) {
                    this.TotalPriceField = value;
                    this.RaisePropertyChanged("TotalPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WeighBridgeApplication.RustiviaService.DbContext.TruckDto Truck {
            get {
                return this.TruckField;
            }
            set {
                if ((object.ReferenceEquals(this.TruckField, value) != true)) {
                    this.TruckField = value;
                    this.RaisePropertyChanged("Truck");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WeighBridgeApplication.RustiviaService.DbContext.WeighBridgeInfoDto WeighBridgeInfo {
            get {
                return this.WeighBridgeInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.WeighBridgeInfoField, value) != true)) {
                    this.WeighBridgeInfoField = value;
                    this.RaisePropertyChanged("WeighBridgeInfo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DriverDto", Namespace="http://schemas.datacontract.org/2004/07/IntroductionMVC5.Service.DTOs")]
    [System.SerializableAttribute()]
    public partial class DriverDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WeighBridgeApplication.RustiviaService.DbContext.SupplierInfoDto SupplierInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Firstname {
            get {
                return this.FirstnameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstnameField, value) != true)) {
                    this.FirstnameField = value;
                    this.RaisePropertyChanged("Firstname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdNumber {
            get {
                return this.IdNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.IdNumberField, value) != true)) {
                    this.IdNumberField = value;
                    this.RaisePropertyChanged("IdNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WeighBridgeApplication.RustiviaService.DbContext.SupplierInfoDto SupplierInfo {
            get {
                return this.SupplierInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.SupplierInfoField, value) != true)) {
                    this.SupplierInfoField = value;
                    this.RaisePropertyChanged("SupplierInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TruckDto", Namespace="http://schemas.datacontract.org/2004/07/IntroductionMVC5.Service.DTOs")]
    [System.SerializableAttribute()]
    public partial class TruckDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool OwnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WeighBridgeApplication.RustiviaService.DbContext.SupplierInfoDto SupplierInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TruckRegNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WeighBridgeApplication.RustiviaService.DbContext.WeighBridgeInfoDto[] WeighBridgeInfoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Own {
            get {
                return this.OwnField;
            }
            set {
                if ((this.OwnField.Equals(value) != true)) {
                    this.OwnField = value;
                    this.RaisePropertyChanged("Own");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WeighBridgeApplication.RustiviaService.DbContext.SupplierInfoDto SupplierInfo {
            get {
                return this.SupplierInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.SupplierInfoField, value) != true)) {
                    this.SupplierInfoField = value;
                    this.RaisePropertyChanged("SupplierInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TruckRegNumber {
            get {
                return this.TruckRegNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.TruckRegNumberField, value) != true)) {
                    this.TruckRegNumberField = value;
                    this.RaisePropertyChanged("TruckRegNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WeighBridgeApplication.RustiviaService.DbContext.WeighBridgeInfoDto[] WeighBridgeInfo {
            get {
                return this.WeighBridgeInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.WeighBridgeInfoField, value) != true)) {
                    this.WeighBridgeInfoField = value;
                    this.RaisePropertyChanged("WeighBridgeInfo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WeighBridgeInfoDto", Namespace="http://schemas.datacontract.org/2004/07/IntroductionMVC5.Service.DTOs")]
    [System.SerializableAttribute()]
    public partial class WeighBridgeInfoDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateInField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateOutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long FirstMassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long NettMassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long SecondMassField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comments {
            get {
                return this.CommentsField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentsField, value) != true)) {
                    this.CommentsField = value;
                    this.RaisePropertyChanged("Comments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateIn {
            get {
                return this.DateInField;
            }
            set {
                if ((this.DateInField.Equals(value) != true)) {
                    this.DateInField = value;
                    this.RaisePropertyChanged("DateIn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateOut {
            get {
                return this.DateOutField;
            }
            set {
                if ((this.DateOutField.Equals(value) != true)) {
                    this.DateOutField = value;
                    this.RaisePropertyChanged("DateOut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long FirstMass {
            get {
                return this.FirstMassField;
            }
            set {
                if ((this.FirstMassField.Equals(value) != true)) {
                    this.FirstMassField = value;
                    this.RaisePropertyChanged("FirstMass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long NettMass {
            get {
                return this.NettMassField;
            }
            set {
                if ((this.NettMassField.Equals(value) != true)) {
                    this.NettMassField = value;
                    this.RaisePropertyChanged("NettMass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long SecondMass {
            get {
                return this.SecondMassField;
            }
            set {
                if ((this.SecondMassField.Equals(value) != true)) {
                    this.SecondMassField = value;
                    this.RaisePropertyChanged("SecondMass");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SupplierInfoDto", Namespace="http://schemas.datacontract.org/2004/07/IntroductionMVC5.Service.DTOs")]
    [System.SerializableAttribute()]
    public partial class SupplierInfoDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WeighBridgeApplication.RustiviaService.DbContext.DriverDto[] DriversField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SupplierCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SupplierNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WeighBridgeApplication.RustiviaService.DbContext.SupplierProductDto[] SupplierProductDtosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WeighBridgeApplication.RustiviaService.DbContext.TruckDto[] TrucksField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WeighBridgeApplication.RustiviaService.DbContext.DriverDto[] Drivers {
            get {
                return this.DriversField;
            }
            set {
                if ((object.ReferenceEquals(this.DriversField, value) != true)) {
                    this.DriversField = value;
                    this.RaisePropertyChanged("Drivers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SupplierCode {
            get {
                return this.SupplierCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SupplierCodeField, value) != true)) {
                    this.SupplierCodeField = value;
                    this.RaisePropertyChanged("SupplierCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SupplierName {
            get {
                return this.SupplierNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SupplierNameField, value) != true)) {
                    this.SupplierNameField = value;
                    this.RaisePropertyChanged("SupplierName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WeighBridgeApplication.RustiviaService.DbContext.SupplierProductDto[] SupplierProductDtos {
            get {
                return this.SupplierProductDtosField;
            }
            set {
                if ((object.ReferenceEquals(this.SupplierProductDtosField, value) != true)) {
                    this.SupplierProductDtosField = value;
                    this.RaisePropertyChanged("SupplierProductDtos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WeighBridgeApplication.RustiviaService.DbContext.TruckDto[] Trucks {
            get {
                return this.TrucksField;
            }
            set {
                if ((object.ReferenceEquals(this.TrucksField, value) != true)) {
                    this.TrucksField = value;
                    this.RaisePropertyChanged("Trucks");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SupplierProductDto", Namespace="http://schemas.datacontract.org/2004/07/IntroductionMVC5.Service.DTOs")]
    [System.SerializableAttribute()]
    public partial class SupplierProductDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SupplierIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SupplierPriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SupplierId {
            get {
                return this.SupplierIdField;
            }
            set {
                if ((this.SupplierIdField.Equals(value) != true)) {
                    this.SupplierIdField = value;
                    this.RaisePropertyChanged("SupplierId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SupplierPrice {
            get {
                return this.SupplierPriceField;
            }
            set {
                if ((this.SupplierPriceField.Equals(value) != true)) {
                    this.SupplierPriceField = value;
                    this.RaisePropertyChanged("SupplierPrice");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SaleDto", Namespace="http://schemas.datacontract.org/2004/07/IntroductionMVC5.Service.DTOs")]
    [System.SerializableAttribute()]
    public partial class SaleDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WeighBridgeApplication.RustiviaService.DbContext.CustomerDto CustomerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExtraInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TruckRegNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WeighBridgeApplication.RustiviaService.DbContext.WeighBridgeInfoDto WeighBridgeInfoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WeighBridgeApplication.RustiviaService.DbContext.CustomerDto Customer {
            get {
                return this.CustomerField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerField, value) != true)) {
                    this.CustomerField = value;
                    this.RaisePropertyChanged("Customer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExtraInfo {
            get {
                return this.ExtraInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtraInfoField, value) != true)) {
                    this.ExtraInfoField = value;
                    this.RaisePropertyChanged("ExtraInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TruckRegNumber {
            get {
                return this.TruckRegNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.TruckRegNumberField, value) != true)) {
                    this.TruckRegNumberField = value;
                    this.RaisePropertyChanged("TruckRegNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WeighBridgeApplication.RustiviaService.DbContext.WeighBridgeInfoDto WeighBridgeInfo {
            get {
                return this.WeighBridgeInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.WeighBridgeInfoField, value) != true)) {
                    this.WeighBridgeInfoField = value;
                    this.RaisePropertyChanged("WeighBridgeInfo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerDto", Namespace="http://schemas.datacontract.org/2004/07/IntroductionMVC5.Service.DTOs")]
    [System.SerializableAttribute()]
    public partial class CustomerDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WeighBridgeApplication.RustiviaService.DbContext.BookingDto[] BookingsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WeighBridgeApplication.RustiviaService.DbContext.BookingDto[] Bookings {
            get {
                return this.BookingsField;
            }
            set {
                if ((object.ReferenceEquals(this.BookingsField, value) != true)) {
                    this.BookingsField = value;
                    this.RaisePropertyChanged("Bookings");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerCode {
            get {
                return this.CustomerCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerCodeField, value) != true)) {
                    this.CustomerCodeField = value;
                    this.RaisePropertyChanged("CustomerCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerName {
            get {
                return this.CustomerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerNameField, value) != true)) {
                    this.CustomerNameField = value;
                    this.RaisePropertyChanged("CustomerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookingDto", Namespace="http://schemas.datacontract.org/2004/07/IntroductionMVC5.Service.DTOs")]
    [System.SerializableAttribute()]
    public partial class BookingDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WeighBridgeApplication.RustiviaService.DbContext.ContainerDto[] ContainersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferenceNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WeighBridgeApplication.RustiviaService.DbContext.ContainerDto[] Containers {
            get {
                return this.ContainersField;
            }
            set {
                if ((object.ReferenceEquals(this.ContainersField, value) != true)) {
                    this.ContainersField = value;
                    this.RaisePropertyChanged("Containers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReferenceNumber {
            get {
                return this.ReferenceNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenceNumberField, value) != true)) {
                    this.ReferenceNumberField = value;
                    this.RaisePropertyChanged("ReferenceNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContainerDto", Namespace="http://schemas.datacontract.org/2004/07/IntroductionMVC5.Service.DTOs")]
    [System.SerializableAttribute()]
    public partial class ContainerDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WeighBridgeApplication.RustiviaService.DbContext.BookingDto BookingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContainerNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateInField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long NettWeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SealnumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long TareWeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TruckRegNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WeighBridgeApplication.RustiviaService.DbContext.WeighBridgeInfoDto WeighBridgeInfoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WeighBridgeApplication.RustiviaService.DbContext.BookingDto Booking {
            get {
                return this.BookingField;
            }
            set {
                if ((object.ReferenceEquals(this.BookingField, value) != true)) {
                    this.BookingField = value;
                    this.RaisePropertyChanged("Booking");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContainerNumber {
            get {
                return this.ContainerNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ContainerNumberField, value) != true)) {
                    this.ContainerNumberField = value;
                    this.RaisePropertyChanged("ContainerNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateIn {
            get {
                return this.DateInField;
            }
            set {
                if ((this.DateInField.Equals(value) != true)) {
                    this.DateInField = value;
                    this.RaisePropertyChanged("DateIn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long NettWeight {
            get {
                return this.NettWeightField;
            }
            set {
                if ((this.NettWeightField.Equals(value) != true)) {
                    this.NettWeightField = value;
                    this.RaisePropertyChanged("NettWeight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sealnumber {
            get {
                return this.SealnumberField;
            }
            set {
                if ((object.ReferenceEquals(this.SealnumberField, value) != true)) {
                    this.SealnumberField = value;
                    this.RaisePropertyChanged("Sealnumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TareWeight {
            get {
                return this.TareWeightField;
            }
            set {
                if ((this.TareWeightField.Equals(value) != true)) {
                    this.TareWeightField = value;
                    this.RaisePropertyChanged("TareWeight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TruckRegNumber {
            get {
                return this.TruckRegNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.TruckRegNumberField, value) != true)) {
                    this.TruckRegNumberField = value;
                    this.RaisePropertyChanged("TruckRegNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WeighBridgeApplication.RustiviaService.DbContext.WeighBridgeInfoDto WeighBridgeInfo {
            get {
                return this.WeighBridgeInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.WeighBridgeInfoField, value) != true)) {
                    this.WeighBridgeInfoField = value;
                    this.RaisePropertyChanged("WeighBridgeInfo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductDto", Namespace="http://schemas.datacontract.org/2004/07/IntroductionMVC5.Service.DTOs")]
    [System.SerializableAttribute()]
    public partial class ProductDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal RustiviaPriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal RustiviaPrice {
            get {
                return this.RustiviaPriceField;
            }
            set {
                if ((this.RustiviaPriceField.Equals(value) != true)) {
                    this.RustiviaPriceField = value;
                    this.RaisePropertyChanged("RustiviaPrice");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RustiviaService.DbContext.IDataService")]
    public interface IDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/AddPurchase", ReplyAction="http://tempuri.org/IDataService/AddPurchaseResponse")]
        void AddPurchase(WeighBridgeApplication.RustiviaService.DbContext.PurchaseDto purchase);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/AddPurchase", ReplyAction="http://tempuri.org/IDataService/AddPurchaseResponse")]
        System.Threading.Tasks.Task AddPurchaseAsync(WeighBridgeApplication.RustiviaService.DbContext.PurchaseDto purchase);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/AddSale", ReplyAction="http://tempuri.org/IDataService/AddSaleResponse")]
        void AddSale(WeighBridgeApplication.RustiviaService.DbContext.SaleDto sale);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/AddSale", ReplyAction="http://tempuri.org/IDataService/AddSaleResponse")]
        System.Threading.Tasks.Task AddSaleAsync(WeighBridgeApplication.RustiviaService.DbContext.SaleDto sale);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/UpdateSale", ReplyAction="http://tempuri.org/IDataService/UpdateSaleResponse")]
        void UpdateSale(WeighBridgeApplication.RustiviaService.DbContext.SaleDto sale);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/UpdateSale", ReplyAction="http://tempuri.org/IDataService/UpdateSaleResponse")]
        System.Threading.Tasks.Task UpdateSaleAsync(WeighBridgeApplication.RustiviaService.DbContext.SaleDto sale);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/UpdatePurchase", ReplyAction="http://tempuri.org/IDataService/UpdatePurchaseResponse")]
        void UpdatePurchase(WeighBridgeApplication.RustiviaService.DbContext.PurchaseDto weighBridgeInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/UpdatePurchase", ReplyAction="http://tempuri.org/IDataService/UpdatePurchaseResponse")]
        System.Threading.Tasks.Task UpdatePurchaseAsync(WeighBridgeApplication.RustiviaService.DbContext.PurchaseDto weighBridgeInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/AddContainerWeight", ReplyAction="http://tempuri.org/IDataService/AddContainerWeightResponse")]
        void AddContainerWeight(WeighBridgeApplication.RustiviaService.DbContext.ContainerDto containerDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/AddContainerWeight", ReplyAction="http://tempuri.org/IDataService/AddContainerWeightResponse")]
        System.Threading.Tasks.Task AddContainerWeightAsync(WeighBridgeApplication.RustiviaService.DbContext.ContainerDto containerDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/UpdateContainer", ReplyAction="http://tempuri.org/IDataService/UpdateContainerResponse")]
        void UpdateContainer(WeighBridgeApplication.RustiviaService.DbContext.ContainerDto containerDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/UpdateContainer", ReplyAction="http://tempuri.org/IDataService/UpdateContainerResponse")]
        System.Threading.Tasks.Task UpdateContainerAsync(WeighBridgeApplication.RustiviaService.DbContext.ContainerDto containerDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/RecoverSale", ReplyAction="http://tempuri.org/IDataService/RecoverSaleResponse")]
        void RecoverSale(WeighBridgeApplication.RustiviaService.DbContext.SaleDto saleDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/RecoverSale", ReplyAction="http://tempuri.org/IDataService/RecoverSaleResponse")]
        System.Threading.Tasks.Task RecoverSaleAsync(WeighBridgeApplication.RustiviaService.DbContext.SaleDto saleDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/RecoverPurchase", ReplyAction="http://tempuri.org/IDataService/RecoverPurchaseResponse")]
        void RecoverPurchase(WeighBridgeApplication.RustiviaService.DbContext.PurchaseDto purchaseDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/RecoverPurchase", ReplyAction="http://tempuri.org/IDataService/RecoverPurchaseResponse")]
        System.Threading.Tasks.Task RecoverPurchaseAsync(WeighBridgeApplication.RustiviaService.DbContext.PurchaseDto purchaseDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetTrucks", ReplyAction="http://tempuri.org/IDataService/GetTrucksResponse")]
        WeighBridgeApplication.RustiviaService.DbContext.TruckDto[] GetTrucks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetTrucks", ReplyAction="http://tempuri.org/IDataService/GetTrucksResponse")]
        System.Threading.Tasks.Task<WeighBridgeApplication.RustiviaService.DbContext.TruckDto[]> GetTrucksAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetDrivers", ReplyAction="http://tempuri.org/IDataService/GetDriversResponse")]
        WeighBridgeApplication.RustiviaService.DbContext.DriverDto[] GetDrivers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetDrivers", ReplyAction="http://tempuri.org/IDataService/GetDriversResponse")]
        System.Threading.Tasks.Task<WeighBridgeApplication.RustiviaService.DbContext.DriverDto[]> GetDriversAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetSuppliers", ReplyAction="http://tempuri.org/IDataService/GetSuppliersResponse")]
        WeighBridgeApplication.RustiviaService.DbContext.SupplierInfoDto[] GetSuppliers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetSuppliers", ReplyAction="http://tempuri.org/IDataService/GetSuppliersResponse")]
        System.Threading.Tasks.Task<WeighBridgeApplication.RustiviaService.DbContext.SupplierInfoDto[]> GetSuppliersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetProducts", ReplyAction="http://tempuri.org/IDataService/GetProductsResponse")]
        WeighBridgeApplication.RustiviaService.DbContext.ProductDto[] GetProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetProducts", ReplyAction="http://tempuri.org/IDataService/GetProductsResponse")]
        System.Threading.Tasks.Task<WeighBridgeApplication.RustiviaService.DbContext.ProductDto[]> GetProductsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetCustomers", ReplyAction="http://tempuri.org/IDataService/GetCustomersResponse")]
        WeighBridgeApplication.RustiviaService.DbContext.CustomerDto[] GetCustomers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetCustomers", ReplyAction="http://tempuri.org/IDataService/GetCustomersResponse")]
        System.Threading.Tasks.Task<WeighBridgeApplication.RustiviaService.DbContext.CustomerDto[]> GetCustomersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetPurchase", ReplyAction="http://tempuri.org/IDataService/GetPurchaseResponse")]
        WeighBridgeApplication.RustiviaService.DbContext.PurchaseDto[] GetPurchase();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetPurchase", ReplyAction="http://tempuri.org/IDataService/GetPurchaseResponse")]
        System.Threading.Tasks.Task<WeighBridgeApplication.RustiviaService.DbContext.PurchaseDto[]> GetPurchaseAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetSales", ReplyAction="http://tempuri.org/IDataService/GetSalesResponse")]
        WeighBridgeApplication.RustiviaService.DbContext.SaleDto[] GetSales();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetSales", ReplyAction="http://tempuri.org/IDataService/GetSalesResponse")]
        System.Threading.Tasks.Task<WeighBridgeApplication.RustiviaService.DbContext.SaleDto[]> GetSalesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetIncompletePurchase", ReplyAction="http://tempuri.org/IDataService/GetIncompletePurchaseResponse")]
        WeighBridgeApplication.RustiviaService.DbContext.PurchaseDto[] GetIncompletePurchase();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetIncompletePurchase", ReplyAction="http://tempuri.org/IDataService/GetIncompletePurchaseResponse")]
        System.Threading.Tasks.Task<WeighBridgeApplication.RustiviaService.DbContext.PurchaseDto[]> GetIncompletePurchaseAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetIncompleteContainers", ReplyAction="http://tempuri.org/IDataService/GetIncompleteContainersResponse")]
        WeighBridgeApplication.RustiviaService.DbContext.ContainerDto[] GetIncompleteContainers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetIncompleteContainers", ReplyAction="http://tempuri.org/IDataService/GetIncompleteContainersResponse")]
        System.Threading.Tasks.Task<WeighBridgeApplication.RustiviaService.DbContext.ContainerDto[]> GetIncompleteContainersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetCompleteContainers", ReplyAction="http://tempuri.org/IDataService/GetCompleteContainersResponse")]
        WeighBridgeApplication.RustiviaService.DbContext.ContainerDto[] GetCompleteContainers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetCompleteContainers", ReplyAction="http://tempuri.org/IDataService/GetCompleteContainersResponse")]
        System.Threading.Tasks.Task<WeighBridgeApplication.RustiviaService.DbContext.ContainerDto[]> GetCompleteContainersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetIncompleteSales", ReplyAction="http://tempuri.org/IDataService/GetIncompleteSalesResponse")]
        WeighBridgeApplication.RustiviaService.DbContext.SaleDto[] GetIncompleteSales();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetIncompleteSales", ReplyAction="http://tempuri.org/IDataService/GetIncompleteSalesResponse")]
        System.Threading.Tasks.Task<WeighBridgeApplication.RustiviaService.DbContext.SaleDto[]> GetIncompleteSalesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/SearchPurchase", ReplyAction="http://tempuri.org/IDataService/SearchPurchaseResponse")]
        WeighBridgeApplication.RustiviaService.DbContext.PurchaseDto[] SearchPurchase(System.DateTime fromDate, System.DateTime toDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/SearchPurchase", ReplyAction="http://tempuri.org/IDataService/SearchPurchaseResponse")]
        System.Threading.Tasks.Task<WeighBridgeApplication.RustiviaService.DbContext.PurchaseDto[]> SearchPurchaseAsync(System.DateTime fromDate, System.DateTime toDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/IsValidUser", ReplyAction="http://tempuri.org/IDataService/IsValidUserResponse")]
        bool IsValidUser(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/IsValidUser", ReplyAction="http://tempuri.org/IDataService/IsValidUserResponse")]
        System.Threading.Tasks.Task<bool> IsValidUserAsync(string userName, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDataServiceChannel : WeighBridgeApplication.RustiviaService.DbContext.IDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataServiceClient : System.ServiceModel.ClientBase<WeighBridgeApplication.RustiviaService.DbContext.IDataService>, WeighBridgeApplication.RustiviaService.DbContext.IDataService {
        
        public DataServiceClient() {
        }
        
        public DataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddPurchase(WeighBridgeApplication.RustiviaService.DbContext.PurchaseDto purchase) {
            base.Channel.AddPurchase(purchase);
        }
        
        public System.Threading.Tasks.Task AddPurchaseAsync(WeighBridgeApplication.RustiviaService.DbContext.PurchaseDto purchase) {
            return base.Channel.AddPurchaseAsync(purchase);
        }
        
        public void AddSale(WeighBridgeApplication.RustiviaService.DbContext.SaleDto sale) {
            base.Channel.AddSale(sale);
        }
        
        public System.Threading.Tasks.Task AddSaleAsync(WeighBridgeApplication.RustiviaService.DbContext.SaleDto sale) {
            return base.Channel.AddSaleAsync(sale);
        }
        
        public void UpdateSale(WeighBridgeApplication.RustiviaService.DbContext.SaleDto sale) {
            base.Channel.UpdateSale(sale);
        }
        
        public System.Threading.Tasks.Task UpdateSaleAsync(WeighBridgeApplication.RustiviaService.DbContext.SaleDto sale) {
            return base.Channel.UpdateSaleAsync(sale);
        }
        
        public void UpdatePurchase(WeighBridgeApplication.RustiviaService.DbContext.PurchaseDto weighBridgeInfo) {
            base.Channel.UpdatePurchase(weighBridgeInfo);
        }
        
        public System.Threading.Tasks.Task UpdatePurchaseAsync(WeighBridgeApplication.RustiviaService.DbContext.PurchaseDto weighBridgeInfo) {
            return base.Channel.UpdatePurchaseAsync(weighBridgeInfo);
        }
        
        public void AddContainerWeight(WeighBridgeApplication.RustiviaService.DbContext.ContainerDto containerDto) {
            base.Channel.AddContainerWeight(containerDto);
        }
        
        public System.Threading.Tasks.Task AddContainerWeightAsync(WeighBridgeApplication.RustiviaService.DbContext.ContainerDto containerDto) {
            return base.Channel.AddContainerWeightAsync(containerDto);
        }
        
        public void UpdateContainer(WeighBridgeApplication.RustiviaService.DbContext.ContainerDto containerDto) {
            base.Channel.UpdateContainer(containerDto);
        }
        
        public System.Threading.Tasks.Task UpdateContainerAsync(WeighBridgeApplication.RustiviaService.DbContext.ContainerDto containerDto) {
            return base.Channel.UpdateContainerAsync(containerDto);
        }
        
        public void RecoverSale(WeighBridgeApplication.RustiviaService.DbContext.SaleDto saleDto) {
            base.Channel.RecoverSale(saleDto);
        }
        
        public System.Threading.Tasks.Task RecoverSaleAsync(WeighBridgeApplication.RustiviaService.DbContext.SaleDto saleDto) {
            return base.Channel.RecoverSaleAsync(saleDto);
        }
        
        public void RecoverPurchase(WeighBridgeApplication.RustiviaService.DbContext.PurchaseDto purchaseDto) {
            base.Channel.RecoverPurchase(purchaseDto);
        }
        
        public System.Threading.Tasks.Task RecoverPurchaseAsync(WeighBridgeApplication.RustiviaService.DbContext.PurchaseDto purchaseDto) {
            return base.Channel.RecoverPurchaseAsync(purchaseDto);
        }
        
        public WeighBridgeApplication.RustiviaService.DbContext.TruckDto[] GetTrucks() {
            return base.Channel.GetTrucks();
        }
        
        public System.Threading.Tasks.Task<WeighBridgeApplication.RustiviaService.DbContext.TruckDto[]> GetTrucksAsync() {
            return base.Channel.GetTrucksAsync();
        }
        
        public WeighBridgeApplication.RustiviaService.DbContext.DriverDto[] GetDrivers() {
            return base.Channel.GetDrivers();
        }
        
        public System.Threading.Tasks.Task<WeighBridgeApplication.RustiviaService.DbContext.DriverDto[]> GetDriversAsync() {
            return base.Channel.GetDriversAsync();
        }
        
        public WeighBridgeApplication.RustiviaService.DbContext.SupplierInfoDto[] GetSuppliers() {
            return base.Channel.GetSuppliers();
        }
        
        public System.Threading.Tasks.Task<WeighBridgeApplication.RustiviaService.DbContext.SupplierInfoDto[]> GetSuppliersAsync() {
            return base.Channel.GetSuppliersAsync();
        }
        
        public WeighBridgeApplication.RustiviaService.DbContext.ProductDto[] GetProducts() {
            return base.Channel.GetProducts();
        }
        
        public System.Threading.Tasks.Task<WeighBridgeApplication.RustiviaService.DbContext.ProductDto[]> GetProductsAsync() {
            return base.Channel.GetProductsAsync();
        }
        
        public WeighBridgeApplication.RustiviaService.DbContext.CustomerDto[] GetCustomers() {
            return base.Channel.GetCustomers();
        }
        
        public System.Threading.Tasks.Task<WeighBridgeApplication.RustiviaService.DbContext.CustomerDto[]> GetCustomersAsync() {
            return base.Channel.GetCustomersAsync();
        }
        
        public WeighBridgeApplication.RustiviaService.DbContext.PurchaseDto[] GetPurchase() {
            return base.Channel.GetPurchase();
        }
        
        public System.Threading.Tasks.Task<WeighBridgeApplication.RustiviaService.DbContext.PurchaseDto[]> GetPurchaseAsync() {
            return base.Channel.GetPurchaseAsync();
        }
        
        public WeighBridgeApplication.RustiviaService.DbContext.SaleDto[] GetSales() {
            return base.Channel.GetSales();
        }
        
        public System.Threading.Tasks.Task<WeighBridgeApplication.RustiviaService.DbContext.SaleDto[]> GetSalesAsync() {
            return base.Channel.GetSalesAsync();
        }
        
        public WeighBridgeApplication.RustiviaService.DbContext.PurchaseDto[] GetIncompletePurchase() {
            return base.Channel.GetIncompletePurchase();
        }
        
        public System.Threading.Tasks.Task<WeighBridgeApplication.RustiviaService.DbContext.PurchaseDto[]> GetIncompletePurchaseAsync() {
            return base.Channel.GetIncompletePurchaseAsync();
        }
        
        public WeighBridgeApplication.RustiviaService.DbContext.ContainerDto[] GetIncompleteContainers() {
            return base.Channel.GetIncompleteContainers();
        }
        
        public System.Threading.Tasks.Task<WeighBridgeApplication.RustiviaService.DbContext.ContainerDto[]> GetIncompleteContainersAsync() {
            return base.Channel.GetIncompleteContainersAsync();
        }
        
        public WeighBridgeApplication.RustiviaService.DbContext.ContainerDto[] GetCompleteContainers() {
            return base.Channel.GetCompleteContainers();
        }
        
        public System.Threading.Tasks.Task<WeighBridgeApplication.RustiviaService.DbContext.ContainerDto[]> GetCompleteContainersAsync() {
            return base.Channel.GetCompleteContainersAsync();
        }
        
        public WeighBridgeApplication.RustiviaService.DbContext.SaleDto[] GetIncompleteSales() {
            return base.Channel.GetIncompleteSales();
        }
        
        public System.Threading.Tasks.Task<WeighBridgeApplication.RustiviaService.DbContext.SaleDto[]> GetIncompleteSalesAsync() {
            return base.Channel.GetIncompleteSalesAsync();
        }
        
        public WeighBridgeApplication.RustiviaService.DbContext.PurchaseDto[] SearchPurchase(System.DateTime fromDate, System.DateTime toDate) {
            return base.Channel.SearchPurchase(fromDate, toDate);
        }
        
        public System.Threading.Tasks.Task<WeighBridgeApplication.RustiviaService.DbContext.PurchaseDto[]> SearchPurchaseAsync(System.DateTime fromDate, System.DateTime toDate) {
            return base.Channel.SearchPurchaseAsync(fromDate, toDate);
        }
        
        public bool IsValidUser(string userName, string password) {
            return base.Channel.IsValidUser(userName, password);
        }
        
        public System.Threading.Tasks.Task<bool> IsValidUserAsync(string userName, string password) {
            return base.Channel.IsValidUserAsync(userName, password);
        }
    }
}
